export const LOGIN_CLICKED = "LOGIN_CLICKED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOGIN_ATTEMPTED = "LOGIN_ATTEMPTED";
export const SIGNUP_CLICKED = "SIGNUP_CLICKED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_ATTEMPTED = "SIGNUP_ATTEMPTED";